# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.CharField(default='', max_length=20, unique='True')),
                ('CurrentSem', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=50)),
                ('hackerearth', models.CharField(blank=True, default='', max_length=500)),
                ('codechef', models.CharField(blank=True, default='', max_length=500)),
                ('spoj', models.CharField(blank=True, default='', max_length=500)),
                ('github', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
