# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_remove_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=200, null=True)),
                ('city', models.CharField(default=None, max_length=200, null=True)),
                ('city_rank', models.IntegerField(default=None, null=True)),
                ('city_total', models.IntegerField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=200, null=True)),
                ('country_rank', models.IntegerField(default=None, null=True)),
                ('country_total', models.IntegerField(default=None, null=True)),
                ('world_rank', models.IntegerField(default=None, null=True)),
                ('world_total', models.IntegerField(default=None, null=True)),
                ('repos', models.IntegerField(default=None, null=True)),
                ('stars', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
