# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default=None, max_length=200)),
                ('site_type', models.CharField(default=None, max_length=100)),
                ('site_active', models.BooleanField(default=False)),
                ('site_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(default=None, max_length=50, unique=True)),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('current_semester', models.IntegerField(default=1, null=True)),
                ('graduation_year', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='CurrentSem',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='RollNo',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='codechef',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='github',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='hackerearth',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='spoj',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='studentsite',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='studentsite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='no_of_sites',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_contribution',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_follower',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_following',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_point',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_ques_solved',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_rating',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_repo',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site_star',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='username',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsite',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Site'),
        ),
    ]
